// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/doriandekoning/IN4392-cloud-computing-lab/worker/design
// --out=$(GOPATH)/src/github.com/doriandekoning/IN4392-cloud-computing-lab/worker
// --version=v1.3.1

package app
